version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password   #数据库超级用户密码
      MYSQL_USER: neoxu   #filerun数据库账户
      MYSQL_PASSWORD: your_filerun_password   #filerun数据库密码
      MYSQL_DATABASE: filerun   #filerun数据库名称
    volumes:
      - /data/docker-img/filerun/db:/var/lib/mysql   #数据库存放的卷

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun   #上面的filerun数据库名称
      FR_DB_USER: neoxu   #上面的filerun数据库账户
      FR_DB_PASS: your_filerun_password   #上面的filerun数据库密码
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8083:80"   #左边的8083端口就是要开放到公网访问的端口，为了避免80端口冲突，我这里映射到8083端口
    volumes:
      - /data/docker-img/filerun/html:/var/www/html
      - /data/docker-img/filerun/user-files:/user-files
